# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfLife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfLife.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfLife.Thing')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShelfLife.User')),
            ],
        ),
    ]
