# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfLife', '0002_thing_userconnections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='user',
        ),
    ]
